
// FIXME: determine if DLC is installed to not crash on missing files
interface fileMetaData {
	name: string[];
	encoding: string;
	type: "decks"|"elements"|"recipes"|"verbs";
	postProcessing?: (input: string) => string;
	dlc: "BoH"|"HoL";
}

export const fileMetaDataList: fileMetaData[] = [
	{name: ["decks", "catalogue_decks.json"], encoding: "utf8", type: "decks", dlc: "BoH"},
	{name: ["decks", "challenges.json"], encoding: "utf8", type: "decks", dlc: "BoH"},
	{name: ["decks", "chats.json"], encoding: "utf8", type: "decks", dlc: "BoH"},
	{name: ["decks", "DLC_HOL_inkling.json"], encoding: "utf8", type: "decks", dlc: "HoL"},
	{name: ["decks", "gathering_decks.json"], encoding: "utf8", type: "decks", dlc: "BoH"},
	{name: ["decks", "incidents_decks.json"], encoding: "utf8", type: "decks", dlc: "BoH"},
	{name: ["elements", "_aspects.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "_aspects_salons.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "_debug.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "_evolutionaspects.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "_groupaspects.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "_order_aspects.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "_prototypes.json"], encoding: "utf8", type: "elements", dlc: "BoH"}, // _ability.fatigued os also in another file
	{name: ["elements", "_resolutionaspects.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "_visitactedaspects.json"], encoding: "utf16le", type: "elements", dlc: "BoH"},
	{name: ["elements", "_visitaspects.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "_visitreadaspects.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "abilities.json"], encoding: "utf8", type: "elements", dlc: "BoH"}, // _ability.fatigued os also in another file
	{name: ["elements", "abilities_setup.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "abilities2.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "abilities3.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "abilities4.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "aspecteditems.json"], encoding: "utf16le", type: "elements", dlc: "BoH"},
	{name: ["elements", "aspects_nx.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "assistance.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "celestial.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "challenge_opportunities.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "circumstances.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "comforts.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "contamination_aspects.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "correspondence _addresses.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "correspondence_elements.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "credits.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "DLC_HOL_instituteaspects_ally.json"], encoding: "utf16le", type: "elements", dlc: "HoL"},
	{name: ["elements", "DLC_HOL_instituteaspects_foe.json"], encoding: "utf16le", type: "elements", dlc: "HoL"},
	{name: ["elements", "DLC_HOL_instituteaspects_mission.json"], encoding: "utf16le", type: "elements", dlc: "HoL"},
	{name: ["elements", "DLC_HOL_manuscripts.json"], encoding: "utf16le", type: "elements", dlc: "HoL"},
	{name: ["elements", "DLC_HOL_meddling.json"], encoding: "utf16le", type: "elements", dlc: "HoL"},
	{name: ["elements", "DLC_HOL_menu.json"], encoding: "utf8", type: "elements", dlc: "HoL"},
	{name: ["elements", "DLC_HOL_misc.json"], encoding: "utf16le", type: "elements", dlc: "HoL"},
	{name: ["elements", "DLC_HOL_ns.json"], encoding: "utf16le", type: "elements", dlc: "HoL"},
	{name: ["elements", "DLC_HOL_salons.json"], encoding: "utf16le", type: "elements", dlc: "HoL"},
	{name: ["elements", "DLC_HOL_stagger_elements.json"], encoding: "utf16le", type: "elements", dlc: "HoL"},
	{name: ["elements", "incidents_n.json"], encoding: "utf8", type: "elements", dlc: "BoH"}, // affair.box dupe record
	{name: ["elements", "incidents_weather.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "journal.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "misc.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "music.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "physical_sphere_text.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "precursors.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "pseudoaspectpreviewtooltips.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "resources.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "skills.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "skills_r.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "tips_hints.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "tlg.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "tomes.json"], encoding: "utf16le", type: "elements", dlc: "BoH", postProcessing: text=>text.replaceAll("\n", "")}, // journalofsirdavidgreene1903 has enters in it's string instead of \n
	{name: ["elements", "uncats.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "visitors.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "visitors_embarking.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "visitors_other.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "visitors_retired.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "xlessons.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["elements", "xlessons_unique.json"], encoding: "utf8", type: "elements", dlc: "BoH"},
	{name: ["recipes", "__debug.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_backstops.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_collections.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_endings_0_histories_present.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_endings_0_histories_unusual_present_record.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_endings_1_histories_record.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_endings_2_determinations.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_histories_hints.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_intercepts.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_legacy.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_legacy_crafting_4a_prenticeplus_ambittable_unfriendly.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "_legacy_crafting_obsolete.json"], encoding: "utf8", type: "recipes", dlc: "BoH"}, // craft.keeper.insects.nectars_moth_larva.chimeric_perilous imago is also in another file
	{name: ["recipes", "_startup_recipes.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "0_consider_decontaminations.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "1_consider_books.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "2a_consider_open.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "2b_consider_generic.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "2c_consider_resolve.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "beasts.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "bookbinding.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "celestial_recipes_time.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "celestial_recipes_weather.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "correspondence.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "correspondence_ordering.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "crafting_0_numina.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "crafting_0_rest.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "crafting_1_chandlery.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "crafting_1_evolutions.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "crafting_1_simplemanipulations.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "crafting_2_keeper.json"], encoding: "utf8", type: "recipes", dlc: "BoH"}, // craft.keeper.insects.nectars_moth_larva.chimeric_perilous imago is also in another file
	{name: ["recipes", "crafting_3_scholar.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "crafting_4b_prentice.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "DLC_HOL_1_lighthouse.json"], encoding: "utf8", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_1_meddling.json"], encoding: "utf8", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_1a_salons_inauguration_end.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_1b_salons_inauguration_ally_foe.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_1b_salons_inauguration_mission.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_2a_salons_blockers_basic.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"}, // salon.hint.guests dupe records x2
	{name: ["recipes", "DLC_HOL_2b_salons_blockers_beverages.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_2c_salons_blockers_repasts.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_3_salons_prototypes.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_3b_salons_routing.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"}, // lastresortfallthroughslnev is also in another file
	{name: ["recipes", "DLC_HOL_cooking.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_correspondence_summoning.json"], encoding: "utf8", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_gathering_2_seasonal.json"], encoding: "utf8", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_interactions_specific.json"], encoding: "utf8", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_leiter.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_manuscripting_soph_improve.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_manuscripting_soph_set.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_manuscripting_write.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_nrs.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_patch_resurrect_incidents.json"], encoding: "utf8", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_prototype_recipes.json"], encoding: "utf8", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_salon_responses.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"}, // lastresortfallthroughslnev is also in another file
	{name: ["recipes", "DLC_HOL_slnbk_languages.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_slnbk_skillls.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_slnbk_skills.json"], encoding: "utf16le", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_understanding_specific.json"], encoding: "utf8", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "DLC_HOL_village_invitations.json"], encoding: "utf8", type: "recipes", dlc: "HoL"},
	{name: ["recipes", "gathering_1_exceptional.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "gathering_2_seasonal.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "other_activities.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "renounce.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "talk_1_visitors.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "talk_2_visitors_payments_tutoring.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "talk_3a_visitors_intercepts.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "talk_3b_visitors_cantread.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "talk_4a_visitors_intros.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "talk_4b_visitors_specific_incidents.json"], encoding: "utf16le", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "talk_5_visitors_generic_consultations.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "talk_5z_visitors_fallthrough_hints.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "talk_6_assistance.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "terrain.json"], encoding: "utf16le", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "understanding_1_numa.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "understanding_2_upskill.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "village_interactions.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "visitors_correspondence_auctions.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "wisdom_commitments.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "wisdom_commitments_exotic.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "z_fallthrough_hints.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["recipes", "z_fallthrough_placeholders.json"], encoding: "utf8", type: "recipes", dlc: "BoH"},
	{name: ["verbs", "celestial.json"], encoding: "utf8", type: "verbs", dlc: "BoH"}, // strange format. might exclude to make logic easier
	{name: ["verbs", "incidents.json"], encoding: "utf8", type: "verbs", dlc: "BoH"}, // strange format. might exclude to make logic easier
	{name: ["verbs", "DLC_HOL_verbs.json"], encoding: "utf8", type: "verbs", dlc: "HoL"},
	{name: ["verbs", "librarian.json"], encoding: "utf8", type: "verbs", dlc: "BoH"},
	{name: ["verbs", "workstations_beds.json"], encoding: "utf8", type: "verbs", dlc: "BoH"},
	{name: ["verbs", "workstations_gathering.json"], encoding: "utf8", type: "verbs", dlc: "BoH"},
	{name: ["verbs", "workstations_legacy.json"], encoding: "utf8", type: "verbs", dlc: "BoH"},
	{name: ["verbs", "workstations_library_world.json"], encoding: "utf8", type: "verbs", dlc: "BoH"},
	{name: ["verbs", "workstations_unusual.json"], encoding: "utf8", type: "verbs", dlc: "BoH"},
	{name: ["verbs", "workstations_upgraded.json"], encoding: "utf8", type: "verbs", dlc: "BoH"},
	{name: ["verbs", "workstations_village.json"], encoding: "utf8", type: "verbs", dlc: "BoH"},
];

export const dlcMaxCounts = fileMetaDataList.reduce((prev, cur): Map<fileMetaData["dlc"], number>=>{
	const count = prev.get(cur.dlc)??0;
	prev.set(cur.dlc, count+1);
	return prev;
}, new Map<fileMetaData["dlc"], number>());
